version: 0.2

phases:
  install:
    commands:
      - Get-Childitem "$env"
      - Get-Childitem "$env\.."
      - Get-Childitem "$env:CODEBUILD_SRC_DIR"
      - Get-Childitem "$env:CODEBUILD_SRC_DIR_PortingAssistantClient"
      - aws s3 cp "s3://$env:PRIVATE_NUGET_FEED_BUCKET" "$env:CODEBUILD_SRC_DIR\NugetFeed" --recursive
  pre_build:
    commands:
      - echo 'prebuild'
  build:
    commands:
      - dotnet restore
      - dotnet build
